version: '3.8'

services:
  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"

  hololens-stream:
    build:
      context: ./hololens-stream  # Separte directory for the hololens-stream container
    container_name: hololens-stream
    depends_on:
      - nats-server
    environment:
      - HOLOLENS_HOST=192.168.2.38  # Set the HoloLens host address here
      - NATS_URL=nats://nats-server:4222
  
  web-server:
    build:
      context: ./web-server  # Separte directory for the web-server container
    container_name: hololens-web-server
    depends_on:
      - nats-server
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats-server:4222
