version: '3.8'

services:
  rtsp-simple-server:
    image: aler9/rtsp-simple-server
    container_name: rtsp-server
    ports:
      - "8554:8554"  # RTSP Port

  ffmpeg-stream:
    build: .  # Build from the Dockerfile in the current directory
    container_name: ffmpeg-stream
    depends_on:
      - rtsp-simple-server
    volumes:
      - ./start_stream.sh:/app/start_stream.sh  # Ensure the script is mapped
    command: /bin/bash /app/start_stream.sh  # Correct shell to run the script
