version: '3.8'

services:
  rtsp-simple-server:
    image: aler9/rtsp-simple-server
    container_name: rtsp-server
    ports:
      - "8554:8554"  # RTSP Port

  ffmpeg-hololens-stream:
    build: .
    container_name: ffmpeg-hololens-stream
    depends_on:
      - rtsp-simple-server
    environment:
      - HOLOLENS_HOST=192.168.2.38  # Set your HoloLens IP here

