version: '3.8'

services:
  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"

  hololens-stream:
    build:
      context: .  # Points to where your Dockerfile is located
    container_name: hololens-stream
    depends_on:
      - nats-server
    environment:
      - HOLOLENS_HOST=192.168.2.38  # Set the HoloLens host address here
      - NATS_URL=nats://nats-server:4222
    volumes:
      - ./viewer:/app/viewer  # Mounts Python script directory
    restart: unless-stopped
