version: '3.8'

services:
  hololens-stream:
    build:
      context: ./hololens-stream  # Points to the directory with your Dockerfile and scripts
    container_name: hololens-stream
    environment:
      - HOLOLENS_HOST=192.168.2.38  # Update this with your HoloLens IP
    ports:
      - "8554:8554"  # Exposes the RTSP port