version: '3.8'

services:
  rtsp-simple-server:
    image: aler9/rtsp-simple-server
    container_name: rtsp-server
    ports:
      - "8554:8554"  # RTSP Port
    restart: unless-stopped

  ffmpeg-stream:
    build: .
    container_name: ffmpeg-stream
    depends_on:
      - rtsp-simple-server
    volumes:
      - ./start_stream.sh:/app/start_stream.sh
    restart: unless-stopped
    command: /app/start_stream.sh
